version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ./RegisterRescueRS/Dockerfile
    container_name: register_rescue_rs_api
    ports:
      - 8092:80
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - TZ=America/Sao_Paulo